name: Reset upload_count

on:
  schedule:
    - cron: "0 3 * * *"  # Meia-noite no horário de Brasília (UTC-3)
  workflow_dispatch:

jobs:
  cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Call Cron Job API
        run: |
          curl -X GET "https://sumaristaai.vercel.app/api/cron" \
          -H "Authorization: Bearer $CRON_SECRET"
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
